### ISSUE TITLE
Payment card logos are dated - use new versions

### ISSUE THREAD

**Issue by williape** [localz/react-native-health-card#1]
both visa and mater card updated their logos:

![mastercard_logo](https://cloud.githubusercontent.com/assets/1552145/19371359/ff030cb0-91fd-11e6-936b-ac80cb5f7e3a.png)
![visa_logo](https://cloud.githubusercontent.com/assets/1552145/19371360/0096038e-91fe-11e6-9c39-6f73695c43d7.png)

**Comment by jxom** [comment]
Paul to fix
